### ISSUE TITLE
Toevoegen URL

### ISSUE THREAD

**Issue by RensTamerus** [CodeCrashersNL/beste-website#26]
Kan de URL van de website worden toegevoegd in de "about" sectie? Voor mensen die al klaar zijn met de opdracht zou het namelijk leuk zijn om af en toe gemakkelijk de website te bezoeken om te zien hoeveel er is toegevoegd. En voor mensen die op dat moment nog bezig zijn met de opdracht is het misschien handig om op een makkelijkere manier de website te kunnen bekijken, aangezien ze dan toch al op GitHub bezig zijn.

**Comment by ChiyuCC** [comment]
Ha Rens, met de "about" sectie bedoel je gewoon de inhoud van de `README.md`, denk ik?

Zeker kan dat! Goede suggestie trouwens 😄.
